### PR TITLE
Fix crimson plant bug, multiplayer pylon bug

### PR DESCRIPTION
**Pull request by HwakYuk**
Img
[Video of working sunken pylon](https://cdn.discordapp.com/attachments/1202610976927784970/1202610978391466014/Terraria__May_the_blocks_be_with_you_2024-02-01_22-44-29.mp4?ex=65ce15c0&is=65bba0c0&hm=6eab2ff5036486deba105f11653b5f272e0610411d54f513776bc077aa75f81d&)

### CODE REVIEW

**Review by Ozzatron — DISMISSED** [review]
Both bug fixes look solid. Thank you.

**Comment by HwakYuk** [comment]
Another bugfix added. Description of this bug is in the discord server bug report channel. Copy of the message:
In `Projectile.FishingCheck()`, if the first bait is truffle worm, it sets `localAI[1] = 1f`. Otherwise `localAI[1]` indicates the caught item. This becomes problematic for multiple bobbers. The first bobber consumes truffle worm and spawns Duke Fishron, and every subsequent bobber which doesn't use truffle worm as a bait catch iron pickaxes, because it has item ID `1`.

There can be various fixes to this bug. The way I came up with is preventing further bobbers to catch something when truffle worm was already used

**Comment by steviegt6** [comment]
Surprised Cal was impacted by this change. Annoying; thanks for the convenience, tModLoader!

**Comment by steviegt6** [comment]
I don't know how much I agree with fixing the Truffle Worm bug in Calamity instead of incorporating it into tModLoader. Has this been reported to them? Is this in line with Vanilla behavior, anything? Are multiple Truffle Worms required to spawn multiple Duke Fishrons?

I'd recommend making the Truffle Worm fix a separate merge request for further discussion.

**Review by steviegt6 — CHANGES_REQUESTED** [review]
Other changes look good; waiting for the Truffle Worm fix to be moved.

**Comment by HwakYuk** [comment]
Truffle worm fix removed. Yes, multiple truffle worms are required to spawn multiple Dukes, but Vanilla seems to assume one bobber a person anyway.

**Review by Ozzatron — APPROVED** [review]

**Review by steviegt6 — APPROVED** [review]

**Pull request merged**
