### PR TITLE
Added respawn feature for Super Dummy

### PR DESCRIPTION
**Pull request by AlienBlox**
I added a respawn ability for the Super Dummy

### CODE REVIEW

**Review by SiriusIlluminati — APPROVED** [review]
Seems like a good addition

**Comment by Ozzatron** [comment]
@AlienBlox What exact problem does respawning the Super Dummy solve? Does it have issues where it dies under certain circumstances?

**Comment by AlienBlox** [comment]
I want to make it last forever unless you delete it manually bc some weapons one shot the dummy

**Comment by Flowaria** [comment]
SuperDummy already have `CheckDead` so this will **duplicate** the dummy once reached life 0.

If you meaning the random despawn issue on MP environment that should not be handled by this way.

**Comment by Ozzatron** [comment]
As this PR is mechanically insolvent, I am closing it.

**Comment by AlienBlox** [comment]
There is an issue with it when used with alicorn on a stick

**Pull request closed without merging**
